### PR TITLE
Sort migrations so migrations for dependent tables occur prior to the tables that depend on them (WIP) 

### PR DESCRIPTION
**Pull request by pdbreen**
I was fiddling with your migration generator, adding dependency sorting so migrations can be run with FK enabled in MySql.   This is WIP that got me close enough that I could tweak the remaining errors by hand.  Just wanted to make you aware its floating around in case you want to pick this up and run with it.  I may circle back myself at some point to turn this into a real PR (biggest thing needed is add support for generating table modification migrations containing the FK constraints that need to be deferred and a lot more testing).

### CODE REVIEW

**Comment by bennett-treptow** [comment]
Awesome! I had thought about adding this back when I first started it, but figured people could just reorder with timestamps as needed because I didn't want to start into dependency resolution!

Thanks for taking a stab, I'll definitely take a look and see what I can add.

**Comment by bennett-treptow** [comment]
@pdbreen I started a graph dependency resolver but circular dependencies were indeed causing issues. I wasn't sure what the best situation would be, if like you had suggested that the foreign keys are created as a separate migration after the table create schemas, or how I implemented it in my version by just sticking the circular dependencies into a transaction. If you want to try to do that and get rid of the idea of the `DependentTable` from my branch, feel free at your leisure. Otherwise, I'll try to get that fixed next week.

My branch: https://github.com/bennett-treptow/laravel-migration-generator/tree/dependency-sort

**Comment by bennett-treptow** [comment]
@pdbreen This is now part of version 4.0.0!

**Comment by pdbreen** [comment]
@bennett-treptow Great news - thank you!

**Pull request closed without merging**
